// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function CheckForUpdates():Promise<desktop.BinaryCheckPayload>;

export function GetBinaryStatus():Promise<desktop.BinaryStatusPayload>;

export function InstallStableUpdate():Promise<desktop.BinaryInstallPayload>;

export function LastUpdateCheck():Promise<desktop.BinaryCheckPayload>;

export function ProbeBinary(arg1:string):Promise<desktop.BinaryVersionPayload>;

export function SetBinarySource(arg1:string,arg2:string):Promise<desktop.BinaryStatusPayload>;
