// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['desktop']['BinaryAPI']['CheckForUpdates']();
}

export function GetBinaryStatus() {
  return window['go']['desktop']['BinaryAPI']['GetBinaryStatus']();
}

export function InstallStableUpdate() {
  return window['go']['desktop']['BinaryAPI']['InstallStableUpdate']();
}

export function LastUpdateCheck() {
  return window['go']['desktop']['BinaryAPI']['LastUpdateCheck']();
}

export function ProbeBinary(arg1) {
  return window['go']['desktop']['BinaryAPI']['ProbeBinary'](arg1);
}

export function SetBinarySource(arg1, arg2) {
  return window['go']['desktop']['BinaryAPI']['SetBinarySource'](arg1, arg2);
}
