// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveConfigPath() {
  return window['go']['desktop']['ConfigAPI']['ActiveConfigPath']();
}

export function ApplyRevision(arg1) {
  return window['go']['desktop']['ConfigAPI']['ApplyRevision'](arg1);
}

export function ApplyTemplate(arg1, arg2) {
  return window['go']['desktop']['ConfigAPI']['ApplyTemplate'](arg1, arg2);
}

export function CompareRevisions(arg1, arg2, arg3) {
  return window['go']['desktop']['ConfigAPI']['CompareRevisions'](arg1, arg2, arg3);
}

export function CompareWithActive(arg1, arg2, arg3) {
  return window['go']['desktop']['ConfigAPI']['CompareWithActive'](arg1, arg2, arg3);
}

export function DetectLegacyConfig() {
  return window['go']['desktop']['ConfigAPI']['DetectLegacyConfig']();
}

export function GetActiveConfig() {
  return window['go']['desktop']['ConfigAPI']['GetActiveConfig']();
}

export function GetDraft(arg1) {
  return window['go']['desktop']['ConfigAPI']['GetDraft'](arg1);
}

export function GetRevision(arg1, arg2) {
  return window['go']['desktop']['ConfigAPI']['GetRevision'](arg1, arg2);
}

export function ImportConfigFile(arg1) {
  return window['go']['desktop']['ConfigAPI']['ImportConfigFile'](arg1);
}

export function ImportLegacyConfig(arg1) {
  return window['go']['desktop']['ConfigAPI']['ImportLegacyConfig'](arg1);
}

export function ListRevisions(arg1, arg2) {
  return window['go']['desktop']['ConfigAPI']['ListRevisions'](arg1, arg2);
}

export function PickConfigFile() {
  return window['go']['desktop']['ConfigAPI']['PickConfigFile']();
}

export function RollbackToRevision(arg1) {
  return window['go']['desktop']['ConfigAPI']['RollbackToRevision'](arg1);
}

export function SaveRevision(arg1) {
  return window['go']['desktop']['ConfigAPI']['SaveRevision'](arg1);
}

export function ValidateConfig(arg1) {
  return window['go']['desktop']['ConfigAPI']['ValidateConfig'](arg1);
}
