// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {desktop} from '../models';

export function ActiveConfigPath():Promise<string>;

export function ApplyRevision(arg1:config.ApplyInput):Promise<desktop.ApplyPayload>;

export function ApplyTemplate(arg1:string,arg2:string):Promise<desktop.RevisionPayload>;

export function CompareRevisions(arg1:string,arg2:string,arg3:string):Promise<desktop.DiffPayload>;

export function CompareWithActive(arg1:string,arg2:string,arg3:string):Promise<desktop.DiffPayload>;

export function DetectLegacyConfig():Promise<desktop.LegacyPayload>;

export function GetActiveConfig():Promise<desktop.ActiveConfigPayload>;

export function GetDraft(arg1:string):Promise<desktop.DraftPayload>;

export function GetRevision(arg1:string,arg2:string):Promise<desktop.RevisionPayload>;

export function ImportLegacyConfig(arg1:string):Promise<desktop.ProfilePayload>;

export function ListRevisions(arg1:string,arg2:number):Promise<desktop.RevisionListPayload>;

export function RollbackToRevision(arg1:config.ApplyInput):Promise<desktop.RevisionPayload>;

export function SaveRevision(arg1:config.SaveInput):Promise<desktop.RevisionPayload>;

export function ValidateConfig(arg1:config.ValidateInput):Promise<desktop.ValidatePayload>;
