// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function ApplyTemplateToProfile(arg1:string,arg2:string):Promise<desktop.ProfilePayload>;

export function CreateProfile(arg1:desktop.CreateProfileRequest):Promise<desktop.ProfilePayload>;

export function CreateProfileFromShareLinks(arg1:desktop.CreateProfileFromShareLinksRequest):Promise<desktop.ShareLinkProfilePayload>;

export function DeleteProfile(arg1:string):Promise<desktop.ProfilesPayload>;

export function DuplicateProfile(arg1:string,arg2:string):Promise<desktop.ProfilePayload>;

export function ExportProfile(arg1:string):Promise<desktop.ExportPayload>;

export function GetProfile(arg1:string):Promise<desktop.ProfilePayload>;

export function ImportProfile(arg1:desktop.CreateProfileRequest):Promise<desktop.ProfilePayload>;

export function ListProfiles():Promise<desktop.ProfilesPayload>;

export function ListRevisions(arg1:string,arg2:number):Promise<desktop.RevisionsPayload>;

export function ListShareLinkBases():Promise<desktop.ShareLinkBasesPayload>;

export function ListTemplates():Promise<desktop.TemplatesPayload>;

export function RenameProfile(arg1:string,arg2:string,arg3:string):Promise<desktop.ProfilePayload>;

export function SetActiveProfile(arg1:string):Promise<desktop.ProfilesPayload>;
