// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTemplateToProfile(arg1, arg2) {
  return window['go']['desktop']['ProfileAPI']['ApplyTemplateToProfile'](arg1, arg2);
}

export function CreateProfile(arg1) {
  return window['go']['desktop']['ProfileAPI']['CreateProfile'](arg1);
}

export function CreateProfileFromShareLinks(arg1) {
  return window['go']['desktop']['ProfileAPI']['CreateProfileFromShareLinks'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['desktop']['ProfileAPI']['DeleteProfile'](arg1);
}

export function DuplicateProfile(arg1, arg2) {
  return window['go']['desktop']['ProfileAPI']['DuplicateProfile'](arg1, arg2);
}

export function ExportProfile(arg1) {
  return window['go']['desktop']['ProfileAPI']['ExportProfile'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['desktop']['ProfileAPI']['GetProfile'](arg1);
}

export function ImportProfile(arg1) {
  return window['go']['desktop']['ProfileAPI']['ImportProfile'](arg1);
}

export function ListProfiles() {
  return window['go']['desktop']['ProfileAPI']['ListProfiles']();
}

export function ListRevisions(arg1, arg2) {
  return window['go']['desktop']['ProfileAPI']['ListRevisions'](arg1, arg2);
}

export function ListShareLinkBases() {
  return window['go']['desktop']['ProfileAPI']['ListShareLinkBases']();
}

export function ListTemplates() {
  return window['go']['desktop']['ProfileAPI']['ListTemplates']();
}

export function RenameProfile(arg1, arg2, arg3) {
  return window['go']['desktop']['ProfileAPI']['RenameProfile'](arg1, arg2, arg3);
}

export function SetActiveProfile(arg1) {
  return window['go']['desktop']['ProfileAPI']['SetActiveProfile'](arg1);
}
