// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['desktop']['RuntimeAPI']['ClearLogs']();
}

export function GetLogs(arg1) {
  return window['go']['desktop']['RuntimeAPI']['GetLogs'](arg1);
}

export function GetRuntimeStatus() {
  return window['go']['desktop']['RuntimeAPI']['GetRuntimeStatus']();
}

export function RestartRuntime(arg1) {
  return window['go']['desktop']['RuntimeAPI']['RestartRuntime'](arg1);
}

export function StartRuntime(arg1) {
  return window['go']['desktop']['RuntimeAPI']['StartRuntime'](arg1);
}

export function StopRuntime() {
  return window['go']['desktop']['RuntimeAPI']['StopRuntime']();
}

export function TailLogs(arg1) {
  return window['go']['desktop']['RuntimeAPI']['TailLogs'](arg1);
}
