// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {runtime} from '../models';

export function ClearLogs():Promise<desktop.LogsPayload>;

export function GetLogs(arg1:runtime.LogQuery):Promise<desktop.LogsPayload>;

export function GetRuntimeStatus():Promise<desktop.RuntimePayload>;

export function RestartRuntime(arg1:string):Promise<desktop.RuntimePayload>;

export function StartRuntime(arg1:string):Promise<desktop.RuntimePayload>;

export function StopRuntime():Promise<desktop.RuntimePayload>;

export function TailLogs(arg1:number):Promise<desktop.LogsPayload>;
