// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnvironment() {
  return window['go']['desktop']['SettingsAPI']['GetEnvironment']();
}

export function GetSettings() {
  return window['go']['desktop']['SettingsAPI']['GetSettings']();
}

export function RemoveLegacyAutostart() {
  return window['go']['desktop']['SettingsAPI']['RemoveLegacyAutostart']();
}

export function SetAutostart(arg1) {
  return window['go']['desktop']['SettingsAPI']['SetAutostart'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['desktop']['SettingsAPI']['UpdateSettings'](arg1);
}
