// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {settings} from '../models';

export function GetEnvironment():Promise<desktop.EnvironmentPayload>;

export function GetSettings():Promise<desktop.SettingsPayload>;

export function RemoveLegacyAutostart():Promise<desktop.SettingsPayload>;

export function SetAutostart(arg1:boolean):Promise<desktop.SettingsPayload>;

export function UpdateSettings(arg1:settings.UpdateInput):Promise<desktop.SettingsPayload>;
