// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildShareLink(arg1) {
  return window['go']['desktop']['ShareAPI']['BuildShareLink'](arg1);
}

export function ParseShareLink(arg1) {
  return window['go']['desktop']['ShareAPI']['ParseShareLink'](arg1);
}

export function ParseShareLinks(arg1) {
  return window['go']['desktop']['ShareAPI']['ParseShareLinks'](arg1);
}

export function SupportedShareSchemes() {
  return window['go']['desktop']['ShareAPI']['SupportedShareSchemes']();
}
