// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function BuildShareLink(arg1:string):Promise<desktop.ShareBuildPayload>;

export function ParseShareLink(arg1:string):Promise<desktop.ShareParsePayload>;

export function ParseShareLinks(arg1:string):Promise<desktop.ShareListPayload>;

export function SupportedShareSchemes():Promise<Array<string>>;
